### ISSUE TITLE
[FEAT] (BE) ITEM 도메인 생성

### ISSUE THREAD

**Issue by seyoung755** [seyoung755/sidedish#2]
## 💡 issue
각 상품에 해당하는 도메인 객체 생성

## 📝 todo
- [ ] ITEM 도메인 만들기
- [ ] 카테고리 도메인 만들기
- [ ] 할인정책 도메인 만들기
- [ ] 이미지 도메인 만들기
